from fossology.exceptions import AuthorizationError as AuthorizationError, FossologyApiError as FossologyApiError
from fossology.obj import Folder as Folder, get_options as get_options
from typing import Any

logger: Any

class Folders:
    def list_folders(self): ...
    def detail_folder(self, folder_id): ...
    def create_folder(self, parent, name, description: Any | None = ..., group: Any | None = ...): ...
    def update_folder(self, folder, name: Any | None = ..., description: Any | None = ...): ...
    def delete_folder(self, folder) -> None: ...
    def copy_folder(self, folder, parent): ...
    def move_folder(self, folder, parent): ...
