from fossology.exceptions import FossologyApiError as FossologyApiError, FossologyUnsupported as FossologyUnsupported
from fossology.obj import License as License, LicenseType as LicenseType, Obligation as Obligation
from typing import Any, List, Tuple

logger: Any

def check_empty_response(response) -> bool: ...

class LicenseEndpoint:
    def list_licenses(self, active: bool = ..., kind: LicenseType = ..., page_size: int = ..., page: int = ..., all_pages: bool = ...) -> List[License]: ...
    def detail_license(self, shortname, group: Any | None = ...) -> Tuple[int, License, List[Obligation]]: ...
    def add_license(self, license: License, merge_request: bool = ...): ...
    def update_license(self, shortname, fullname: str = ..., text: str = ..., url: str = ..., risk: int = ...): ...
