from fossology.exceptions import AuthorizationError as AuthorizationError, FossologyApiError as FossologyApiError
from fossology.obj import Licenses as Licenses, Summary as Summary, Upload as Upload, get_options as get_options
from typing import Any

logger: Any

class Uploads:
    def detail_upload(self, upload_id: int, group: str = ..., wait_time: int = ...) -> Upload: ...
    def upload_file(self, folder, file: Any | None = ..., vcs: Any | None = ..., url: Any | None = ..., server: Any | None = ..., description: Any | None = ..., access_level: Any | None = ..., ignore_scm: bool = ..., group: Any | None = ..., wait_time: int = ...): ...
    def upload_summary(self, upload, group: Any | None = ...): ...
    def upload_licenses(self, upload, group: str = ..., agent: Any | None = ..., containers: bool = ...): ...
    def delete_upload(self, upload, group: Any | None = ...) -> None: ...
    def list_uploads(self, folder: Any | None = ..., group: Any | None = ..., recursive: bool = ..., page_size: int = ..., page: int = ..., all_pages: bool = ...): ...
    def move_upload(self, upload, folder, group: Any | None = ...) -> None: ...
    def copy_upload(self, upload, folder) -> None: ...
