import fossology
from fossology.obj import Agents, Folder as Folder, Upload as Upload
from typing import Any, Dict

logger: Any
console: Any
formatter: Any

def foss_server() -> str: ...
def foss_agents() -> Agents: ...
def foss_schedule_agents() -> Dict: ...
def foss_user_agents() -> Dict: ...
def foss_user(foss_user_agents) -> Dict: ...
def foss_token(foss_server: str) -> str: ...
def foss(foss_server: str, foss_token: str, foss_agents: Agents) -> fossology.Fossology: ...
def test_file_path() -> str: ...
def upload_folder(foss: fossology.Fossology) -> Folder: ...
def move_folder(foss: fossology.Fossology) -> Folder: ...
def upload(foss: fossology.Fossology, test_file_path: str) -> Upload: ...
def scanned_upload(foss: fossology.Fossology, test_file_path: str, foss_schedule_agents: Dict) -> Upload: ...
