import fossology
from fossology.obj import License

shortname: str

def test_license(): ...
def test_another_license(): ...
def test_detail_license_error(foss_server: str, foss: fossology.Fossology): ...
def test_detail_license_not_found(foss: fossology.Fossology): ...
def test_detail_license(foss: fossology.Fossology): ...
def test_list_licenses_error(foss_server: str, foss: fossology.Fossology): ...
def test_get_all_licenses(foss: fossology.Fossology): ...
def test_get_all_licenses_first_page(foss: fossology.Fossology): ...
def test_get_all_candidate_licenses(foss: fossology.Fossology): ...
def test_add_license_error(foss_server: str, foss: fossology.Fossology, test_license: License): ...
def test_add_license_already_exists(foss_server: str, foss: fossology.Fossology, monkeypatch, test_license: License): ...
def test_add_license_and_get_by_shortname(foss: fossology.Fossology, test_license: License, monkeypatch): ...
def test_patch_license_error(foss_server: str, foss: fossology.Fossology, test_license: License): ...
def test_patch_license_and_get_by_shortname(foss: fossology.Fossology, test_another_license: License): ...
def test_license_to_json(test_license: License): ...
def test_obligation_object() -> None: ...
