from fossology import Fossology as Fossology
from fossology.obj import Upload as Upload

def test_report_nogroup(foss: Fossology, upload: Upload): ...
def test_download_report_nogroup(foss: Fossology, upload: Upload): ...
def test_generate_report(foss: Fossology, upload: Upload): ...
def test_report_error(foss_server: str, foss: Fossology, upload: Upload): ...
def test_download_report_error(foss_server: str, foss: Fossology): ...
