from fossology import Fossology as Fossology
from fossology.obj import Upload as Upload
from typing import Dict

def test_unpack_jobs(foss: Fossology, upload: Upload): ...
def test_nogroup_jobs(foss: Fossology, upload: Upload, foss_schedule_agents: Dict): ...
def test_schedule_jobs(foss: Fossology, upload: Upload, foss_schedule_agents: Dict): ...
def test_schedule_job_error(foss_server: str, foss: Fossology, upload: Upload): ...
def test_list_jobs_error(foss_server: str, foss: Fossology): ...
def test_detail_job_error(foss_server: str, foss: Fossology): ...
def test_paginated_list_jobs(foss: Fossology, scanned_upload: Upload): ...
