from fossology import Fossology as Fossology

def test_list_folders_error(foss_server: str, foss: Fossology): ...
def test_create_folder_nogroup(foss: Fossology): ...
def test_create_folder(foss: Fossology): ...
def test_create_folder_same_name_different_case(foss: Fossology): ...
def test_create_folder_no_parent(foss: Fossology): ...
def test_create_folder_returns_200_but_folder_does_not_exists(foss_server: str, foss: Fossology): ...
def test_create_folder_error(foss_server: str, foss: Fossology): ...
def test_update_folder(foss: Fossology): ...
def test_update_folder_error(foss_server: str, foss: Fossology): ...
def test_move_folder(foss: Fossology): ...
def test_copy_folder(foss: Fossology): ...
def test_put_folder_error(foss_server: str, foss: Fossology): ...
def test_delete_folder(foss: Fossology): ...
def test_delete_folder_error(foss_server: str, foss: Fossology): ...
