from fossology import Fossology as Fossology
from fossology.obj import Upload

def test_search_nogroup(foss: Fossology): ...
def test_search(foss: Fossology, upload): ...
def test_search_nothing_found(foss: Fossology, upload): ...
def test_search_directory(foss: Fossology, upload): ...
def test_search_upload(foss: Fossology, upload): ...
def test_search_upload_does_not_exist(foss: Fossology): ...
def test_search_error(foss_server: str, foss: Fossology): ...
def test_filesearch(foss: Fossology, scanned_upload: Upload): ...
def test_filesearch_nogroup(foss: Fossology): ...
def test_filesearch_error(foss_server: str, foss: Fossology): ...
