from fossology import Fossology
from typing import Any

logger: Any
console: Any
formatter: Any

def test_generate_token_wrong_date(foss_server: str): ...
def test_generate_token_too_long(foss_server: str): ...
def test_generate_token_errors(foss_server: str): ...
def test_backward_compatibility(foss_server: str, foss_token: str): ...
def test_unknown_user(foss: Fossology): ...
def test_list_users(foss: Fossology): ...
def test_get_self_error(foss_server: str, foss: Fossology): ...
def test_get_self_with_agents(foss_server: str, foss: Fossology, foss_user: dict, foss_user_agents: dict): ...
def test_detail_user_with_agents(foss_server: str, foss: Fossology, foss_user: dict, foss_user_agents: dict): ...
def test_list_users_with_agents(foss_server: str, foss: Fossology, foss_user: dict, foss_user_agents: dict): ...
def test_list_users_error(foss_server: str, foss: Fossology): ...
def test_detail_user(foss: Fossology): ...
def test_delete_user(foss_server: str, foss: Fossology): ...
def test_noversion(foss_server: str, foss: Fossology): ...
