from fossology import Fossology as Fossology
from fossology.obj import Folder, Upload

def test_upload_sha1(foss: Fossology, upload: Upload): ...
def test_get_upload_unauthorized(foss: Fossology, upload: Upload): ...
def test_get_upload_error(foss: Fossology, foss_server: str): ...
def test_upload_nogroup(foss: Fossology, upload_folder: Folder, test_file_path: str): ...
def test_get_uploads(foss: Fossology, upload_folder: Folder, test_file_path: str): ...
def test_upload_from_vcs(foss: Fossology): ...
def test_upload_ignore_scm(foss: Fossology): ...
def test_upload_from_url(foss: Fossology): ...
def test_upload_from_server(foss: Fossology): ...
def test_empty_upload(foss: Fossology): ...
def test_upload_error(foss: Fossology, foss_server: str, test_file_path: str): ...
def test_move_upload_nogroup(foss: Fossology, upload: Upload, move_folder: Folder): ...
def test_move_upload(foss: Fossology, upload: Upload, move_folder: Folder): ...
def test_copy_upload(foss: Fossology, upload: Upload): ...
def test_move_upload_to_non_existing_folder(foss: Fossology, upload: Upload): ...
def test_copy_upload_to_non_existing_folder(foss: Fossology, upload: Upload): ...
def test_upload_summary(foss: Fossology, scanned_upload: Upload): ...
def test_upload_licenses(foss: Fossology, scanned_upload: Upload): ...
def test_delete_unknown_upload_unknown_group(foss: Fossology): ...
def test_paginated_list_uploads(foss: Fossology, upload: Upload, test_file_path: str): ...
