name: CLI Tests

on: 
  pull_request:
    paths:
      - '**cli**'

jobs:
  test-latest:
    name: foss_cli tests (latest Fossology)
    runs-on: ubuntu-latest

    container:
      image: python:3.12-slim
      volumes:
        - /tmp:/tmp

    services:
      fossology:
        image: fossology/fossology:latest
        ports:
          - 8081:80
        volumes:
          - /tmp:/tmp

    steps:
      - uses: actions/checkout@v1
      - name: Install host dependencies
        run: |
          apt-get -qq update
          apt-get install -qq bzip2 gcc git nmap xz-utils
          rm -rf /var/lib/apt/lists/*
      - name: Install Python dependencies
        run: |
          pip install uv
          uv sync --all-extras
      - name: Install files in shared volume
        run: |
          tar xvf tests/files/base-files_10.3-debian10-test.tar.bz2 -C /tmp
      - name: Check services
        run: nmap fossology -p 80
      - name: Run tests
        run: |
          uv run coverage run --source=fossology -m pytest tests/test_foss_cli*.py
          uv run coverage report -m
        continue-on-error: true
